require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  SuggestExtensions: false
  Exclude:
    - '**/bin/*'

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*'

Naming/VariableNumber:
  EnforcedStyle: snake_case

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Metrics/ParameterLists:
  Exclude:
    - 'app/components/**/*'
